route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.mail.ru:465'
        require_tls: false
        auth_username: 'usermail@mail.ru'
        auth_password: "ptJxsdlf393Jb5iR"
        from: 'usermail@mail.ru'
        to: 'usermail1@mail.ru'
    
